/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package checkyourstudy;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class AYT extends javax.swing.JFrame {

    /**
     * Creates new form AYT
     */
    public AYT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jred1 = new javax.swing.JRadioButton();
        jred2 = new javax.swing.JRadioButton();
        jred3 = new javax.swing.JRadioButton();
        jred4 = new javax.swing.JRadioButton();
        ed_ileri = new javax.swing.JButton();
        jred5 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jrm21 = new javax.swing.JRadioButton();
        jrm22 = new javax.swing.JRadioButton();
        jrm23 = new javax.swing.JRadioButton();
        jrm24 = new javax.swing.JRadioButton();
        m2_ileri = new javax.swing.JButton();
        jrm25 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jrcoğ1 = new javax.swing.JRadioButton();
        jrcoğ2 = new javax.swing.JRadioButton();
        jrcoğ3 = new javax.swing.JRadioButton();
        jrcoğ4 = new javax.swing.JRadioButton();
        coğ_ileri = new javax.swing.JButton();
        jrcoğ5 = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jrtar1 = new javax.swing.JRadioButton();
        jrtar2 = new javax.swing.JRadioButton();
        jrtar3 = new javax.swing.JRadioButton();
        jrtar4 = new javax.swing.JRadioButton();
        tar_ileri = new javax.swing.JButton();
        jrtar5 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Net Sayıları");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Edebiyat");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(jred1);
        jred1.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jred1.setText("40 - 35 ve arası");

        buttonGroup1.add(jred2);
        jred2.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jred2.setText("35-30 ve arası");

        buttonGroup1.add(jred3);
        jred3.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jred3.setText("30-25 ve arası");

        buttonGroup1.add(jred4);
        jred4.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jred4.setText("25-20 ve arası");

        ed_ileri.setBackground(new java.awt.Color(153, 153, 255));
        ed_ileri.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        ed_ileri.setForeground(new java.awt.Color(255, 255, 255));
        ed_ileri.setText("İleri");
        ed_ileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ed_ileriActionPerformed(evt);
            }
        });

        buttonGroup1.add(jred5);
        jred5.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jred5.setText("20 ve aşağısı");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(ed_ileri))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jred3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jred2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jred1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jred4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jred5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jred1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jred2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jred3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jred4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jred5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(ed_ileri)
                .addGap(26, 26, 26))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Matematik");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(jrm21);
        jrm21.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrm21.setText("40 - 35 ve arası");

        buttonGroup1.add(jrm22);
        jrm22.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrm22.setText("35-30 ve arası");

        buttonGroup1.add(jrm23);
        jrm23.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrm23.setText("30-25 ve arası");

        buttonGroup1.add(jrm24);
        jrm24.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrm24.setText("25-20 ve arası");

        m2_ileri.setBackground(new java.awt.Color(153, 153, 255));
        m2_ileri.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        m2_ileri.setForeground(new java.awt.Color(255, 255, 255));
        m2_ileri.setText("İleri");
        m2_ileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2_ileriActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrm25);
        jrm25.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrm25.setText("20 ve aşağısı");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(m2_ileri))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrm23, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrm22, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrm21, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrm24, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrm25, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jrm21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrm22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrm23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrm24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrm25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(m2_ileri)
                .addGap(26, 26, 26))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(153, 153, 255));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sosyal Bilimler2");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(jrcoğ1);
        jrcoğ1.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrcoğ1.setText("40 - 35 ve arası");

        buttonGroup1.add(jrcoğ2);
        jrcoğ2.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrcoğ2.setText("35-30 ve arası");

        buttonGroup1.add(jrcoğ3);
        jrcoğ3.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrcoğ3.setText("30-25 ve arası");

        buttonGroup1.add(jrcoğ4);
        jrcoğ4.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrcoğ4.setText("25-20 ve arası");

        coğ_ileri.setBackground(new java.awt.Color(153, 153, 255));
        coğ_ileri.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        coğ_ileri.setForeground(new java.awt.Color(255, 255, 255));
        coğ_ileri.setText("İleri");
        coğ_ileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coğ_ileriActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrcoğ5);
        jrcoğ5.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrcoğ5.setText("20 ve aşağısı");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrcoğ3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrcoğ2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrcoğ1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrcoğ4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrcoğ5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(coğ_ileri)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jrcoğ1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrcoğ2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrcoğ3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrcoğ4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrcoğ5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(coğ_ileri)
                .addGap(26, 26, 26))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBackground(new java.awt.Color(153, 153, 255));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fen Bilimleri2");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(jrtar1);
        jrtar1.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrtar1.setText("40 - 35 ve arası");

        buttonGroup1.add(jrtar2);
        jrtar2.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrtar2.setText("35-30 ve arası");

        buttonGroup1.add(jrtar3);
        jrtar3.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrtar3.setText("30-25 ve arası");

        buttonGroup1.add(jrtar4);
        jrtar4.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrtar4.setText("25-20 ve arası");

        tar_ileri.setBackground(new java.awt.Color(153, 153, 255));
        tar_ileri.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        tar_ileri.setForeground(new java.awt.Color(255, 255, 255));
        tar_ileri.setText("İleri");
        tar_ileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tar_ileriActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrtar5);
        jrtar5.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrtar5.setText("20 ve aşağısı");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrtar3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrtar2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrtar1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrtar4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrtar5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(tar_ileri)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jrtar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrtar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrtar3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrtar4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrtar5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tar_ileri)
                .addGap(26, 26, 26))
        );

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Geri");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ed_ileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ed_ileriActionPerformed
        // TODO add your handling code here:
        
        try{

        if(jred1.isSelected()){

            JOptionPane.showMessageDialog(null, " Günde 40 Edebiyat sorusu çözmelisin ! ");
        }
        else if(jred2.isSelected()){

            JOptionPane.showMessageDialog(null, " Günde 60 Edebiyat sorusu çözmelisin ! ");

        }
        else if(jred3.isSelected()){

            JOptionPane.showMessageDialog(null, " Günde 80 Edebiyat sorusu çözmelisin ! ");

        }
        else if(jred4.isSelected()){

            JOptionPane.showMessageDialog(null, " Günde 100 Edebiyat sorusu çözmelisin ! ");

        }
        else if(jred5.isSelected()){

            JOptionPane.showMessageDialog(null, " Günde 120 Edebiyat sorusu çözmelisin ! ");

        }
    }//GEN-LAST:event_ed_ileriActionPerformed
catch(Exception e){
         
         JOptionPane.showMessageDialog(rootPane,  "ERROR");
     }
     }
    
    private void m2_ileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2_ileriActionPerformed
        // TODO add your handling code here:
        
        try{
        
        if(jrm21.isSelected()){
            
            JOptionPane.showMessageDialog(null, " Günde 50 Matematik2 ve 20 Geometri sorusu çözmelisin ! ");
        }
        else if(jrm22.isSelected()){
            
            JOptionPane.showMessageDialog(null, " Günde 60 Matematik2 ve 30 Geometri sorusu çözmelisin ! ");
        }
        else if(jrm23.isSelected()){
            
            JOptionPane.showMessageDialog(null, " Günde 70 Matematik2 ve 40 Geometri sorusu çözmelisin ! ");
        }
        else if(jrm24.isSelected()){
            
            JOptionPane.showMessageDialog(null, " Günde 80 Matematik2 ve 50 Geometri sorusu çözmelisin ! ");
        }
        else if(jrm25.isSelected()){
            
            JOptionPane.showMessageDialog(null, " Günde 90 Matematik2 ve 60 Geometri sorusu çözmelisin ! ");
        }
    }//GEN-LAST:event_m2_ileriActionPerformed
catch(Exception e){
         
         JOptionPane.showMessageDialog(rootPane,  "ERROR");
     }
     }
    
    private void coğ_ileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coğ_ileriActionPerformed
        // TODO add your handling code here:
        
        try{
        
        if(jrcoğ1.isSelected()){
            
            JOptionPane.showMessageDialog(null,  "Neti en düşük dersine ağırlık vererek 30 soru çözmelisin!");
        }
        else if(jrcoğ2.isSelected()){
            
             JOptionPane.showMessageDialog(null,  "Neti en düşük dersine ağırlık vererek 50 soru çözmelisin!");
        }
         else if(jrcoğ3.isSelected()){
            
             JOptionPane.showMessageDialog(null,  "Neti en düşük dersine ağırlık vererek 70 soru çözmelisin!");
        }
         else if(jrcoğ4.isSelected()){
            
             JOptionPane.showMessageDialog(null,  "Neti en düşük dersine ağırlık vererek 80 soru çözmelisin!");
        }
         else if(jrcoğ5.isSelected()){
            
             JOptionPane.showMessageDialog(null,  "Neti en düşük dersine ağırlık vererek 90 soru çözmelisin!");
        }
    }//GEN-LAST:event_coğ_ileriActionPerformed
catch(Exception e){
         
         JOptionPane.showMessageDialog(rootPane,  "ERROR");
     }
     }
    
    private void tar_ileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tar_ileriActionPerformed
        // TODO add your handling code here:
        
        try{
        
        if(jrtar1.isSelected()){
            
            JOptionPane.showMessageDialog(null,  "Neti en düşük dersine ağırlık vererek 30 soru çözmelisin!");
        }
        else if(jrtar2.isSelected()){
            
             JOptionPane.showMessageDialog(null,  "Neti en düşük dersine ağırlık vererek 50 soru çözmelisin!");
        }
        else if(jrtar3.isSelected()){
            
             JOptionPane.showMessageDialog(null,  "Neti en düşük dersine ağırlık vererek 70 soru çözmelisin!");
        }
        else if(jrtar4.isSelected()){
            
             JOptionPane.showMessageDialog(null,  "Neti en düşük dersine ağırlık vererek 80 soru çözmelisin!");
        }
        else if(jrtar5.isSelected()){
            
             JOptionPane.showMessageDialog(null,  "Neti en düşük dersine ağırlık vererek 90 soru çözmelisin!");
        }
        
    }//GEN-LAST:event_tar_ileriActionPerformed
catch(Exception e){
         
         JOptionPane.showMessageDialog(rootPane,  "ERROR");
     }
     }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        HomePage hp = new HomePage();
        
        HomePage frame = new HomePage();
        
        frame.setDefaultCloseOperation(CheckYourStudyApp.EXIT_ON_CLOSE);
        frame.setSize(800,450);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AYT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AYT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AYT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AYT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AYT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton coğ_ileri;
    private javax.swing.JButton ed_ileri;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jrcoğ1;
    private javax.swing.JRadioButton jrcoğ2;
    private javax.swing.JRadioButton jrcoğ3;
    private javax.swing.JRadioButton jrcoğ4;
    private javax.swing.JRadioButton jrcoğ5;
    private javax.swing.JRadioButton jred1;
    private javax.swing.JRadioButton jred2;
    private javax.swing.JRadioButton jred3;
    private javax.swing.JRadioButton jred4;
    private javax.swing.JRadioButton jred5;
    private javax.swing.JRadioButton jrm21;
    private javax.swing.JRadioButton jrm22;
    private javax.swing.JRadioButton jrm23;
    private javax.swing.JRadioButton jrm24;
    private javax.swing.JRadioButton jrm25;
    private javax.swing.JRadioButton jrtar1;
    private javax.swing.JRadioButton jrtar2;
    private javax.swing.JRadioButton jrtar3;
    private javax.swing.JRadioButton jrtar4;
    private javax.swing.JRadioButton jrtar5;
    private javax.swing.JButton m2_ileri;
    private javax.swing.JButton tar_ileri;
    // End of variables declaration//GEN-END:variables
}
