/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package checkyourstudy;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class TYT extends javax.swing.JFrame {

    /**
     * Creates new form TYT
     */
    public TYT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jrm11 = new javax.swing.JRadioButton();
        jrm12 = new javax.swing.JRadioButton();
        jrm13 = new javax.swing.JRadioButton();
        jrm14 = new javax.swing.JRadioButton();
        jrm15 = new javax.swing.JRadioButton();
        m1_ileri = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jrtr1 = new javax.swing.JRadioButton();
        jrtr2 = new javax.swing.JRadioButton();
        jrtr3 = new javax.swing.JRadioButton();
        jrtr4 = new javax.swing.JRadioButton();
        tr_ileri = new javax.swing.JButton();
        jrtr5 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jrfen1 = new javax.swing.JRadioButton();
        jrfen2 = new javax.swing.JRadioButton();
        jrfen3 = new javax.swing.JRadioButton();
        fen_ileri = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jrsos1 = new javax.swing.JRadioButton();
        jrsos2 = new javax.swing.JRadioButton();
        jrsos3 = new javax.swing.JRadioButton();
        sos_ileri = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(896, 410));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Net Sayıları");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(94, 94, 94))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 21, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Matematik");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(jrm11);
        jrm11.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrm11.setText("40 - 35 ve arası");

        buttonGroup1.add(jrm12);
        jrm12.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrm12.setText("35-30 ve arası");

        buttonGroup1.add(jrm13);
        jrm13.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrm13.setText("30-25 ve arası");

        buttonGroup1.add(jrm14);
        jrm14.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrm14.setText("25-20 ve arası");

        buttonGroup1.add(jrm15);
        jrm15.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrm15.setText("20 ve aşağısı");

        m1_ileri.setBackground(new java.awt.Color(153, 153, 255));
        m1_ileri.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        m1_ileri.setForeground(new java.awt.Color(255, 255, 255));
        m1_ileri.setText("İleri");
        m1_ileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1_ileriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrm15, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrm14, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrm13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrm12, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrm11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(m1_ileri)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jrm11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrm12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrm13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrm14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrm15)
                .addGap(27, 27, 27)
                .addComponent(m1_ileri)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 97, -1, 281));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Türkçe");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(jrtr1);
        jrtr1.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrtr1.setText("40 - 35 ve arası");

        buttonGroup1.add(jrtr2);
        jrtr2.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrtr2.setText("35-30 ve arası");

        buttonGroup1.add(jrtr3);
        jrtr3.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrtr3.setText("30-25 ve arası");

        buttonGroup1.add(jrtr4);
        jrtr4.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrtr4.setText("25-20 ve arası");

        tr_ileri.setBackground(new java.awt.Color(153, 153, 255));
        tr_ileri.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        tr_ileri.setForeground(new java.awt.Color(255, 255, 255));
        tr_ileri.setText("İleri");
        tr_ileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tr_ileriActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrtr5);
        jrtr5.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrtr5.setText("20 ve aşağısı");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrtr3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrtr2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrtr1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrtr4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrtr5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(tr_ileri)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jrtr1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrtr2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrtr3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrtr4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrtr5)
                .addGap(28, 28, 28)
                .addComponent(tr_ileri)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 97, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(153, 153, 255));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fen Bilimleri");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        buttonGroup1.add(jrfen1);
        jrfen1.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrfen1.setText("20-15 ve arası");

        buttonGroup1.add(jrfen2);
        jrfen2.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrfen2.setText("15-10 ve arası");

        buttonGroup1.add(jrfen3);
        jrfen3.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrfen3.setText("10 ve aşağısı");

        fen_ileri.setBackground(new java.awt.Color(153, 153, 255));
        fen_ileri.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        fen_ileri.setForeground(new java.awt.Color(255, 255, 255));
        fen_ileri.setText("İleri");
        fen_ileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fen_ileriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrfen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrfen1)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addComponent(jrfen3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fen_ileri)
                .addGap(54, 54, 54))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jrfen1)
                .addGap(18, 18, 18)
                .addComponent(jrfen2)
                .addGap(18, 18, 18)
                .addComponent(jrfen3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fen_ileri)
                .addGap(38, 38, 38))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 97, -1, 281));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(153, 153, 255));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sosyal Bilimler");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(jrsos1);
        jrsos1.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrsos1.setText("20-15 ve arası");

        buttonGroup1.add(jrsos2);
        jrsos2.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrsos2.setText("15-10 ve arası");

        buttonGroup1.add(jrsos3);
        jrsos3.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jrsos3.setText("10 ve aşağısı");

        sos_ileri.setBackground(new java.awt.Color(153, 153, 255));
        sos_ileri.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        sos_ileri.setForeground(new java.awt.Color(255, 255, 255));
        sos_ileri.setText("İleri");
        sos_ileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sos_ileriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jrsos1)
                            .addComponent(jrsos2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jrsos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(sos_ileri)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jrsos1)
                .addGap(18, 18, 18)
                .addComponent(jrsos2)
                .addGap(18, 18, 18)
                .addComponent(jrsos3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sos_ileri)
                .addGap(39, 39, 39))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 97, -1, 281));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Geri");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 395, 80, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tr_ileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tr_ileriActionPerformed
        // TODO add your handling code here:
        
        try{
        
        if(jrtr1.isSelected()){
            
            JOptionPane.showMessageDialog(null, " Günde 40 Dil Bilgisi ve 20 Paragraf sorusu çözmelisin ! ");
        }
        else if(jrtr2.isSelected()){
            
            JOptionPane.showMessageDialog(null, " Günde 50 Dil Bilgisi ve 30 Paragraf sorusu çözmelisin ! ");
            
        }
        else if(jrtr3.isSelected()){
            
            JOptionPane.showMessageDialog(null, " Günde 60 Dil Bilgisi ve 40 Paragraf sorusu çözmelisin ! ");
            
        }
        else if(jrtr4.isSelected()){
            
            JOptionPane.showMessageDialog(null, " Günde 70 Dil Bilgisi ve 50 Paragraf sorusu çözmelisin ! ");
            
        }
        else if(jrtr5.isSelected()){
            
            JOptionPane.showMessageDialog(null, " Günde 80 Dil Bilgisi ve 60 Paragraf sorusu çözmelisin ! ");
        
        
    }
    }//GEN-LAST:event_tr_ileriActionPerformed
     catch(Exception e){
         
         JOptionPane.showMessageDialog(rootPane,  "ERROR");
     }
     }
    
    private void m1_ileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1_ileriActionPerformed
        // TODO add your handling code here:
        
       try{
        
        if(jrm11.isSelected()){
            
            JOptionPane.showMessageDialog(null,  " Günde 50 Matematik1 ve 20 Geometri sorusu çözmelisin ! ");
        }
        else if(jrm12.isSelected()){
            
            JOptionPane.showMessageDialog(null,  " Günde 60 Matematik1 ve 30 Geometri sorusu çözmelisin ! ");
        }
        else if(jrm13.isSelected()){
            
            JOptionPane.showMessageDialog(null,  " Günde 70 Matematik1 ve 40 Geometri sorusu çözmelisin ! ");
        }
        else if(jrm14.isSelected()){
            
            JOptionPane.showMessageDialog(null,  " Günde 80 Matematik1 ve 50 Geometri sorusu çözmelisin ! ");
        }
        else if(jrm15.isSelected()){
            
            JOptionPane.showMessageDialog(null,  " Günde 90 Matematik1 ve 60 Geometri sorusu çözmelisin ! ");
        }
        
    }//GEN-LAST:event_m1_ileriActionPerformed
      catch(Exception e){
         
         JOptionPane.showMessageDialog(rootPane,  "ERROR");
     }
     }
    
    private void sos_ileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sos_ileriActionPerformed
        // TODO add your handling code here:
        
        try{
        
        if(jrsos1.isSelected()){
            
            JOptionPane.showMessageDialog(null,  " Günde Tarih, Coğrafya, Felsefe ve Din Bilgisi \n" +
"derslerinden en düşük netine ağırlık vererek 60 soru çözmelisin ! ");
        }
        else if(jrsos2.isSelected()){
            JOptionPane.showMessageDialog(null,  " Günde Tarih, Coğrafya, Felsefe ve Din Bilgisi \n" +
"derslerinden en düşük netine ağırlık vererek 80 soru çözmelisin ! ");
            
        }
        
         else if(jrsos3.isSelected()){
            JOptionPane.showMessageDialog(null,  " Günde Tarih, Coğrafya, Felsefe ve Din Bilgisi \n" +
"derslerinden en düşük netine ağırlık vererek 100 soru çözmelisin ! ");
            
        }
    }//GEN-LAST:event_sos_ileriActionPerformed
catch(Exception e){
         
         JOptionPane.showMessageDialog(rootPane,  "ERROR");
     }
     }
    
    private void fen_ileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fen_ileriActionPerformed
        // TODO add your handling code here:
        
        try{
        
        if(jrfen1.isSelected()){
            
            JOptionPane.showMessageDialog(null,  " Günde Fizik, Kimya ve Biyoloji derslerinden en \n" +
"düşük netine ağırlık vererek 60 soru çözmelisin !");
        }
        else if(jrfen2.isSelected()){
            
            JOptionPane.showMessageDialog(null,  " Günde Fizik, Kimya ve Biyoloji derslerinden en \n" +
"düşük netine ağırlık vererek 80 soru çözmelisin !");
        }
        else if(jrfen3.isSelected()){
            
            JOptionPane.showMessageDialog(null,  " Günde Fizik, Kimya ve Biyoloji derslerinden en \n" +
"düşük netine ağırlık vererek 100 soru çözmelisin !");
        }
    }//GEN-LAST:event_fen_ileriActionPerformed
catch(Exception e){
         
         JOptionPane.showMessageDialog(rootPane,  "ERROR");
     }
     }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        HomePage hp = new HomePage();
        
        HomePage frame = new HomePage();
        
        frame.setDefaultCloseOperation(CheckYourStudyApp.EXIT_ON_CLOSE);
        frame.setSize(800,450);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TYT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TYT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TYT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TYT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TYT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton fen_ileri;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jrfen1;
    private javax.swing.JRadioButton jrfen2;
    private javax.swing.JRadioButton jrfen3;
    private javax.swing.JRadioButton jrm11;
    private javax.swing.JRadioButton jrm12;
    private javax.swing.JRadioButton jrm13;
    private javax.swing.JRadioButton jrm14;
    private javax.swing.JRadioButton jrm15;
    private javax.swing.JRadioButton jrsos1;
    private javax.swing.JRadioButton jrsos2;
    private javax.swing.JRadioButton jrsos3;
    private javax.swing.JRadioButton jrtr1;
    private javax.swing.JRadioButton jrtr2;
    private javax.swing.JRadioButton jrtr3;
    private javax.swing.JRadioButton jrtr4;
    private javax.swing.JRadioButton jrtr5;
    private javax.swing.JButton m1_ileri;
    private javax.swing.JButton sos_ileri;
    private javax.swing.JButton tr_ileri;
    // End of variables declaration//GEN-END:variables
}
